### ISSUE TITLE
Set a HTML Grammar to .vue files

### ISSUE THREAD

**Issue by BevilaquaBruno** [atom/grammar-selector#55]
When i open a .vue file the grammar setted is plain text, can i change this ?
i want when i open a .vue file,this file it already comes open in .html grammar.
Thank you.
![image](https://user-images.githubusercontent.com/34351545/38703747-78bd28ae-3e7a-11e8-8793-12713cfea4d6.png)

**Comment by Arcanemagus** [comment]
You can find instructions for customizing language recognition in the [Flight Manual](https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition).

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
